# /config/pkg/integral.yaml

template:
#
  - sensor:
#
    - name: Sun Elevation
      unique_id: sun_elevation
      state: >-
        {% set x = state_attr('sun.sun', 'elevation')|float(0) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ 0 }}
        {% endif %}
      state_class: measurement
      unit_of_measurement: '°'
      icon: "mdi:sun-angle"

    - name: Fake Export W
      unique_id: fake_export_w
      state: >-
        {% set a = states('sensor.sun_elevation')|float %}
        {% if a > 0 %}
          {{ (a * 8 * 6.76)|round(1) }}
        {% else %}
          {{ 1 }}
        {% endif %}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

    - name: Fake Solar W
      unique_id: fake_solar_w
      state: >-
        {% set a = states('sensor.sun_elevation')|float %}
        {% if a > 0 %}
          {{ (a * 8 * 6.76)|round(1) }}
        {% else %}
          {{ 1 }}
        {% endif %}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

    - name: "U1 Power"
      unique_id: u1_power
      state: >-
        {% set a = states('sensor.u1_nominal_real_power')|int(0) %}
        {% set b = states('sensor.u1_load')|int(0) %}
        {% set x = (a * b / 100)|int(0) %}
        {{ x }}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

### ### ###

sensor:

  - platform: integration
    source: sensor.u1_power
    name: EM UPS1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.athom_p1_energy_power
    name: EM Athom P1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.fake_export_w
    name: Fake Export kWh
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.fake_solar_w
    name: Fake Solar kWh
    unit_prefix: k
    round: 2

# EOF
