# /config/pkg/integral.yaml

template:
#
  - sensor:
#
    - name: SR1 Water Level
      unique_id: sr1_water_level
      state: >-
        {% set a = states('sensor.tas_sr1_sr04_distance')|float(0) %}
        {% set b = 30 %}
        {% if a > 0 %}
          {{ ((b - a) / 100)|round(2) }}
        {% endif %}
      state_class: measurement
      unit_of_measurement: "m"
      icon: "mdi:leak"

    - name: Sun Elevation
      state: "{{ state_attr('sun.sun', 'elevation') }}"
      state_class: measurement
      unit_of_measurement: '°'
      icon: "mdi:sun-angle"

    - name: Fake Export W
      state: >-
        {% set a = states('sensor.sun_elevation')|float %}
        {% if a > 0 %}
          {{ (a * 8 * 6.76)|round(1) }}
        {% else %}
          {{ 1 }}
        {% endif %}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

    - name: Fake Solar W
      state: >-
        {% set a = states('sensor.sun_elevation')|float %}
        {% if a > 0 %}
          {{ (a * 8 * 6.76)|round(1) }}
        {% else %}
          {{ 1 }}
        {% endif %}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

    - name: "U1 Power"
      state: >-
        {% set a = states('sensor.u1_nominal_real_power')|int(0) %}
        {% set b = states('sensor.u1_load')|int(0) %}
        {% set x = (a * b / 100)|int(0) %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"

### ### ###

sensor:

  - platform: integration
    source: sensor.eb3_active_power_l1
    name: EM3 L1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.eb3_active_power_l2
    name: EM3 L2
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.eb3_active_power_l3
    name: EM3 L3
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.u1_power
    name: EM UPS1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.athom_p1_energy_power
    name: EM Athom P1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.fake_export_w
    name: Fake Export kWh
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.fake_solar_w
    name: Fake Solar kWh
    unit_prefix: k
    round: 2

# EOF
