# /config/pkg/water.yaml

sensor:
#
  - platform: filter
    name: "T8 Ultrasonic Filter"
    entity_id: sensor.t8_ultrasonic
    filters:
      - filter: outlier
        window_size: 7
        radius: 0.5

### ### ###

template:
#
  - sensor:
#
    - name: T8 Water Level
      unique_id: t8_water_level
      state: >-
        {% set a = states('sensor.t8_ultrasonic_filter')|float(0.0) %}
        {% set b = 0.40 %}
        {{ (b - a)|round(3) }}
      state_class: measurement
      device_class: distance
      unit_of_measurement: "m"
      icon: "mdi:leak"

# EOF
